config/routes.rb
App::Application.routes.draw do
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => 'artists#index'
  resources :artists do
    resources :songs do
      resources :pictures
    end
  end
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name
  has_many :songs
  attr_accessible :songs
  accepts_nested_attributes_for :songs
end

app/models/posts/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :integer, :name
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :artist_id, :lyric, :name, :image
  belongs_to :artist
  mount_uploader :image, ImageUploader
  has_many :pictures
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
     @songs = Song.find(params[:id])
  end

  def new
    @artist = Artist.new
    @artist.songs.build
  end

  def create
    @artist = Artist.new(params[:artist])
    
    if @artist.save
      redirect_to @artist, :notice => "Successfully created artist."
    else
      render :action => 'new'
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update_attributes(params[:artist])
      redirect_to @artist, :notice  => "Successfully updated artist."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_url, :notice => "Successfully destroyed artist."
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @artist = Artist.find(params[:artist_id])
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @artists = Artist.all
    @songs = @artists.songs
  end
  def show
    @artist = Artist.find(params[:artist_id])
    @song = Song.find(params[:id])
  end
  def edit
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.find(params[:id])
  end
  def update
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.find(params[:id])
    if @song.update_attributes(params[:song])
      redirect_to @artist, :notice  => "Successfully updated Song!"
    else
      render :action => 'edit'
    end
  end
  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new    
  end
  def create
    
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(params[:song])
    if @song.save
      redirect_to @artist, :notice => "Successfully created artist."
    else
      render :action => 'new'
    end
  end
  def destroy
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.find(params[:id])
    if @song.destroy
      redirect_to artist_path(@artist), :notice => "Song Succesfully Deleted"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end
  def show
    @user = current_user
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                artists_path, :class => 'btn' %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artists/index.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.id %></td>
        <td><%= link_to artist.name, artist_path(artist) %></td>
        <td><%=l artist.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_artist_path(artist), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      artist_path(artist),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_artist_path,
            :class => 'btn btn-primary' %>

app/views/artists/new.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artists/show.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @artist.name %></dd>
</dl>

<% @artist.songs.each do |song| %>
<ul>
	<li><%= link_to song.name, artist_song_path(@artist, song)%></li>
</ul>
<% end %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              artists_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_artist_path(@artist), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              artist_path(@artist),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_artist_song_path(@artist),
            :class => 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">MusicU</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Artists", artists_path  %></li>
              <li><%= link_to "Albums", "/path/under/construction"  %></li>
              <li><%= link_to "Songs", "/path/not/complete"  %></li>
            </ul>
            <form class ="navbar-search pull-right" action>
            	<input type="text" class="search-query span4" placeholder="Search">
            </form>
          </div>   	
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span10">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span2">
            <div class="well sidebar-nav">
            <center>
              <h3>Account</h3>
              <ul class="nav nav-list">
                
                <li><%= link_to current_user, "/user/edit"  %></li>
                <li><%= link_to "Login", "/login"  %></li>
                <li><%= link_to "Logout", "/logout"  %></li>
              </ul>
              <h3> Popular Content </h3>
              <ul class= "nav nav-list">
              	<li> <%= link_to "Artists", artists_path %> </li>
              	<li> Songs  </li>
              	<li> Albums </li>
              	<li> Pictures </li>
              	<li> Covers </li>
              	<li> Live  </li>	
              </ul>
             </center>
            </div><!--/.well -->
          </div>
         <!--/span-->
        </div>
        <!--/row-->
      <!--footer>
        <p>&copy; Company 2013</p>
      </footer-->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/holder/holder.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>
    <script>
      !function ($) {
        $(function(){
          
          $('#myCarousel').carousel()
        })
      }(window.jQuery)
    </script>

  </body>
</html>

app/views/pictures/index.html.erb
<h1> Test page </h1>
<p> This page is testing the routing to display all pictures</p>
<p> [Page Still in Build]</p>

app/views/songs/_form.html.erb
<%= form_for [@artist, @song], :html => {:multipart => true} do |f| %>
	<p>
    <%= f.label :lyric, :class => 'control-label' %>
    
    <%= f.text_area :lyric, :class => 'text_area' %>
    </p>
    <p>
    <%= f.label :name, :class => 'control-label' %>
   
    <%= f.text_field :name, :class => 'text_field' %>
	</p>
	<p>
		<%= f.file_field :image %>
	</p>
	<p> 
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), artist_songs_path, :class => 'btn' %>
	</p>  
<% end %>

<!--% #:html => { :class => 'form-horizontal' } %-->
<!--div class="control-group"-->
<!--div class="controls"-->

<!--/div>
  </div>
  <div class="control-group"-->
  
 <!--div class="controls"-->
 
    <!--/div>
  </div>

  <div class="form-actions"-->
<!--/div-->
  	

app/views/songs/edit.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/index.html.erb
<h1> Blank - Not Built</h1>

app/views/songs/new.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1>Add a Song and Lyrics </h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/show.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <center><h1><%= @song.name %> by <%= @artist.name %></h1></center>
  <center>
  	<audio controls width ="500"></audio>
  </center>
</div>

<!--dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @song.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lyric) %>s:</strong></dt>
  <dd><%= @song.lyric %></dd>
</dl-->
<div class ="row">
	<div class ="span6">
		<ul class="thumbnails">
		  <li class="span6">
		    <div class="thumbnail center">
		      <img data-src="holder.js/360x270" alt="">
		      <center><h3><%= link_to "Pictures", artist_song_pictures_path(@artist, @song) %></h3>
		      <div class ="row">
		      	<center>
		      		<div class = "span 1"><img src = "http://arts.mit.edu/wp-content/uploads/blank-image-590.jpg" width="65" height="50" alt=""></div>	
		      		<div class = "span 1"><img src="http://arts.mit.edu/wp-content/uploads/blank-image-590.jpg" width="65" height="50" alt=""></div>	
		      		<div class = "span 1"><img src="http://arts.mit.edu/wp-content/uploads/blank-image-590.jpg" width="65" height="50" alt=""></div>	
		      		<div class = "span 1"><img src="http://arts.mit.edu/wp-content/uploads/blank-image-590.jpg" width="65" height="50" alt=""></div>	
		      		<div class = "span 1"><img src="http://arts.mit.edu/wp-content/uploads/blank-image-590.jpg" width="65" height="50" alt=""></div>
		      		<div class = "span 1"><img src="http://arts.mit.edu/wp-content/uploads/blank-image-590.jpg" width="65" height="50" alt=""></div>		
		      	</center>
		      </div>
		      <p>View pictures uploaded about "<%= @song.name %>"</p></center>
		    </div>
		  </li>
	<div class="span6">
		  <div class = "row">
		  	<div class = "span2">
		  		<ul class= "thumbnail">
		  			<center>
			  			<h3> <%= link_to "Comments", "/path/for/comments" %>, <%= link_to "Tweets", "/path/for/tweets" %> <%= link_to "and Statuses", "/path/for/facebook" %> about "<%= @song.name%>"</h3>
			  				<p> [Place Holder]</p><br />
			  				<p> --> In Build</p><br />
			  				<p> [Place Holder]</p><br />
			  				<p> --> In Build</p><br />
			  				<p> [Place Holder]</p><br />
			  				<p> --> In Build</p><br />
		  			</center>
		  		</ul>
		  		
		  	</div>
		  	<div class ="span4">
		  		<ul class = "thumbnails">
				  <li class ="span4">
				  	<div class = "thumbnail center">
				  		<img data-src = "holder.js/360x270" alt="">
				  		<center><h3><%= link_to "Covers and Remixes", "/path" %></h3>
				  			<video controls height="250" width="360"></video>
				      <p>View other interpretations of "<%= @song.name %>" !</p></center>
				  	</div>
				  	</li>
				  	<!--li class ="span4">
				  	<div class = "thumbnail center">
				  		<img data-src = "holder.js/360x270" alt="">
				  		<center><h3><%= link_to "Live Performances", "/path" %></h3>
				      <p>View footage of "<%= @song.name %>" live !</p></center>
				  	</div>
				  	</li-->
				  </ul>
				</div>
			</div>
			</div>
		</ul>
	</div><!--for thumbnail columns-->
	<div class = "span4">
		<div class = "row">
			<div class = "span4">
				<div id="myCarousel" class="carousel slide">
				      <div class="carousel-inner center">
				        <div class="item active">
				          <%= image_tag @song.image %>
				          <div class="container center">
				            <div class="carousel-caption">
				              <center><h1>Lyrics</h1></center>
				              <center><p class="lead"><%= truncate(@song.lyric, :length => 100, :separator => ' ; ')%></p></center>
				              <center><a class="btn btn-large btn-primary right" href="#">View</a></center>
				            </div>
				          </div>
				        </div>
				        <div class="item">
				          <img src="http://www.tristateindie.com/wp-content/uploads/2013/02/metallica-1a.jpg" alt="">
				          <div class="container">
				            <div class="carousel-caption">
				              <center><h1>Subscribe to <%= @artist.name %></h1></center>
				              <center>
				              <p class="lead">Subscribe in order to integrate <%= @artist.name%>'s content into your account!</p>
				              <a class="btn btn-large btn-warning" href="#">Subscribe</a>
				              </center>
				            </div>
				          </div>
				        </div>
				        <div class="item">
				          <img src="http://videokeman.com/image/pics/MetallicasongPics1c0rRU9psFSdsUM.jpg" alt="">
				          <div class="container">
				            <div class="carousel-caption">
				              <center><h1>News</h1></center>
				              <center>
				              <p class="lead">View news about <%= @artist.name %></p>
				              <a class="btn btn-large btn-primary" href="http://www.music-news.com/">Browse</a>
				              </center>
				            </div>
				          </div>
				        </div>
				      </div>
				      <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
				      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
				    </div>
				 </div> 
				<div class = "span4">
		  			<ul class = "thumbnails">
					  <li class ="span4">
					  	<div class = "thumbnail center">
				  			<img data-src = "holder.js/360x270" alt="">
				  			<center><h3><%= link_to "Live Performances", "/path" %></h3>
				  				<video controls height ="120" width ="180"></video>
				      		<p>View footage of "<%= @song.name %>" live !</p></center>
				  		</div>
				  		</li>
				  	</ul>
				 
					  	
					
					
					
				</div>
			</div>
	</div><!--carousel column-->
</div><!--row div-->

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              artist_path(@artist), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_artist_song_path(@artist), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              artist_song_path(@artist, @song),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <a class="btn btn-large btn-info pull-right" href="facebook.com">Share on Facebook</a>
  <a class="btn btn-large btn-primary pull-right" href="twitter.com">Share on Twitter</a>         
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<% title "My Content" %>

<div id="myCarousel" class="carousel slide">
      <div class="carousel-inner center">
        <div class="item active">
          <img src="http://images4.fanpop.com/image/photos/17300000/Metallica-metallica-17311296-1600-1200.jpg" alt="">
          <div class="container center">
            <div class="carousel-caption">
              <h1>Photos</h1>
              <p class="lead">View your Photos!</p>
              <a class="btn btn-large btn-primary right" href="#">View</a>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://images6.fanpop.com/image/photos/32200000/metallica-metallica-32272631-800-640.png" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Covers and Remixes</h1>
              <p class="lead">View your Covers and Remixes!</p>
              <a class="btn btn-large btn-warning" href="#">View</a>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://images.fanpop.com/images/image_uploads/Metallica-metallica-150433_850_600.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Live Performances</h1>
              <p class="lead">View your favourited live performances</p>
              <a class="btn btn-large btn-primary" href="#">View</a>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
    </div>
<br />
<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>TestTestTestTest</h1>